import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";

import { font } from "@cp/theme";
import Navbar from "@cp/navbar.client";

import "./globals.css";


export const metadata: Metadata = {
  title: "LimeBlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-style-none">
      <body
        className={`${font.kleeOne.className} antialiased w-screen min-h-[calc(100vh-4rem)] overflow-x-hidden overflow-y-scroll bg-background text-foreground scroll-style-none`}
      >
        <Navbar />
        <div className="relative w-full h-full mt-16 mb-0 overflow-hidden py-0">
          <div className="w-full overflow-x-hidden" id="main">
            {children}
          </div>
          {/* <Footer /> */}
        </div>
        {/* <BackToTopButton /> */}
        <Analytics />
      </body>
    </html>
  );
}
