import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Navbar from "@cp/navbar.client";

import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LimeBlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-style-none">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen min-h-[calc(100vh-4rem)] overflow-x-hidden overflow-y-scroll bg-background text-foreground scroll-style-none`}
      >
        <Navbar />
        <div className="relative w-full h-full mt-16 mb-0 overflow-hidden py-0">
          <div className="w-full overflow-x-hidden" id="main">
            {children}
          </div>
          {/* <Footer /> */}
        </div>
        {/* <BackToTopButton />
        <Analytics /> */}
      </body>
    </html>
  );
}
